### ISSUE TITLE
Add symbolic links to generated figures

### ISSUE THREAD

**Issue by timmens** [OpenSourceEconomics/ada_topics#6]
Fix `TODO` in [task_create_screencasts.py](../blob/main/src/ada_topics/task_create_screencasts.py).

**Comment by hmgaudecker** [comment]
Will be fixed in #8. 

See https://github.com/OpenSourceEconomics/epp_topics/tree/main/src/epp_topics/pandas/inspecting_and_summarizing/screencast/public for an example how the links are specified.
